databases:
  - name: mysistem
    databaseName: mysistem
    user: mysistem

services:
  - type: web
    name: mysistem
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysistem
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
